In [1]:
print('Hello World')

Hello World


In [3]:
x = [45,77,63,12,45,'Pune',78.44]
type(x)

list

In [4]:
x = (45,77,63,12,45,'Pune',78.44)
type(x)

tuple

In [6]:
x = {45,77,63,12,45,'Pune',78.44, 77, 12, 12}
type(x)

set

In [7]:
x

{12, 45, 63, 77, 78.44, 'Pune'}

In [8]:
x = {4:77,6:12,5:'Pune',11:78.44}
type(x)

dict

In [9]:
x[5]

'Pune'

In [15]:
num = 562359865891276517858612851726418375646756758745786

In [16]:
num

562359865891276517858612851726418375646756758745786

In [17]:
2**128

340282366920938463463374607431768211456

In [19]:
import numpy as np

In [20]:
num = np.array([23,11,45,78,95,27,52])

In [21]:
num

array([23, 11, 45, 78, 95, 27, 52])

In [22]:
num.size

7

In [23]:
num.dtype

dtype('int64')

In [24]:
num.ndim

1

In [25]:
num.max()

95

In [26]:
num.min()

11

In [27]:
num = np.array([23,11,45,78,95,27,52], dtype=np.int8)

In [28]:
num

array([23, 11, 45, 78, 95, 27, 52], dtype=int8)

In [29]:
num = np.array([23,11,45,78,95,27,52], dtype=np.uint8)
num

array([23, 11, 45, 78, 95, 27, 52], dtype=uint8)

In [30]:
num = np.array([23,11,45,78,95,27,52, 67.23, 11.22])

In [31]:
num

array([23.  , 11.  , 45.  , 78.  , 95.  , 27.  , 52.  , 67.23, 11.22])

In [32]:
num.dtype

dtype('float64')

In [33]:
num[0]

23.0

In [34]:
num = np.array([23,11,45,78,95,27,52, True])

In [35]:
num

array([23, 11, 45, 78, 95, 27, 52,  1])

In [36]:
num.std()

30.495901363953813

In [37]:
num.mean()

41.5

In [38]:
num.sum()

332

In [39]:
num 

array([23, 11, 45, 78, 95, 27, 52,  1])

In [40]:
num + 12

array([ 35,  23,  57,  90, 107,  39,  64,  13])

In [41]:
num / 0.5

array([ 46.,  22.,  90., 156., 190.,  54., 104.,   2.])

In [42]:
num * 10

array([230, 110, 450, 780, 950, 270, 520,  10])

In [43]:
num1 = np.array([24,61,25,58,85,17,82,11])

In [44]:
num + num1

array([ 47,  72,  70, 136, 180,  44, 134,  12])

In [45]:
num / num1

array([0.95833333, 0.18032787, 1.8       , 1.34482759, 1.11764706,
       1.58823529, 0.63414634, 0.09090909])

In [46]:
num > num1

array([False, False,  True,  True,  True,  True, False, False])

In [47]:
num

array([23, 11, 45, 78, 95, 27, 52,  1])

In [48]:
num > 50

array([False, False, False,  True,  True, False,  True, False])

In [49]:
num[num > 50]

array([78, 95, 52])

In [50]:
num[2:6]

array([45, 78, 95, 27])

In [51]:
num[2:]

array([45, 78, 95, 27, 52,  1])

In [52]:
num[:4]

array([23, 11, 45, 78])

In [53]:
M = np.array([[4,5,6],[2,1,9],[7,6,2],[0,1,5]])

In [54]:
M

array([[4, 5, 6],
       [2, 1, 9],
       [7, 6, 2],
       [0, 1, 5]])

In [55]:
M.dtype

dtype('int64')

In [56]:
M.shape

(4, 3)

In [57]:
M.size

12

In [58]:
M.min()

0

In [59]:
M.max()

9

In [60]:
M

array([[4, 5, 6],
       [2, 1, 9],
       [7, 6, 2],
       [0, 1, 5]])

In [61]:
M.min(axis=1)

array([4, 1, 2, 0])

In [62]:
M.min(axis=0)

array([0, 1, 2])

In [63]:
M.mean()

4.0

In [64]:
M.mean(axis=1)

array([5., 4., 5., 2.])

In [65]:
M.T

array([[4, 2, 7, 0],
       [5, 1, 6, 1],
       [6, 9, 2, 5]])

In [66]:
M.reshape(6,2)

array([[4, 5],
       [6, 2],
       [1, 9],
       [7, 6],
       [2, 0],
       [1, 5]])

In [67]:
M.reshape(3,4)

array([[4, 5, 6, 2],
       [1, 9, 7, 6],
       [2, 0, 1, 5]])

In [68]:
M.reshape(-1,6)

array([[4, 5, 6, 2, 1, 9],
       [7, 6, 2, 0, 1, 5]])

In [69]:
M.flatten()

array([4, 5, 6, 2, 1, 9, 7, 6, 2, 0, 1, 5])

In [70]:
M

array([[4, 5, 6],
       [2, 1, 9],
       [7, 6, 2],
       [0, 1, 5]])

In [71]:
M * 10

array([[40, 50, 60],
       [20, 10, 90],
       [70, 60, 20],
       [ 0, 10, 50]])

In [72]:
M[1:3, 0:2]

array([[2, 1],
       [7, 6]])

In [73]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [76]:
np.arange(1,15,2)

array([ 1,  3,  5,  7,  9, 11, 13])

In [77]:
np.arange(20,1,-3)

array([20, 17, 14, 11,  8,  5,  2])

In [78]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [81]:
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [82]:
x = np.zeros(10, dtype=np.int8)
x

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [83]:
x = np.zeros([3,3], dtype=np.int8)
x

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [84]:
x = np.ones([3,3], dtype=np.int8)
x

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [85]:
x = np.zeros([3,3], dtype=np.int8) + 8
x

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]], dtype=int8)

In [88]:
num = np.array([5, 6, 2, 8, 9, 1, 3, 7, 4, 0])
num[5:].sort()

In [89]:
num

array([5, 6, 2, 8, 9, 0, 1, 3, 4, 7])

In [90]:
np.linspace(1,8,6)

array([1. , 2.4, 3.8, 5.2, 6.6, 8. ])