In [2]:
# data: Salary_Data.csv

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
df = pd.read_csv('Salary_Data.csv')
df.head()

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [109]:
df.shape

(30, 2)

In [111]:
x = df['YearsExperience'].values
x = x.reshape(30, 1)
y = df['Salary']

In [113]:
# Holdout
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, 
                                                   random_state= 0)

In [115]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_train, y_train)
print('training acc:', lr.score(x_train, y_train))
print('testing acc:', lr.score(x_test, y_test))

training acc: 0.9395413526983522
testing acc: 0.9779208335417602


#### KFold

In [118]:
from sklearn.model_selection import KFold

In [120]:
kf = KFold(n_splits= 5, random_state= 0, shuffle= True)

In [122]:
test

array([ 0,  3, 12, 15, 21, 25])

In [124]:
for train, test in kf.split(x, y):
    print(train, '\n', test)

[ 0  1  3  4  5  6  7  8  9 11 12 14 15 16 17 18 19 20 21 22 23 25 27 29] 
 [ 2 10 13 24 26 28]
[ 0  1  2  3  4  6  7  8  9 10 12 13 14 15 18 19 20 21 23 24 25 26 28 29] 
 [ 5 11 16 17 22 27]
[ 0  2  3  4  5  6  7  9 10 11 12 13 15 16 17 18 19 21 22 24 25 26 27 28] 
 [ 1  8 14 20 23 29]
[ 0  1  2  3  5  8 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27 28 29] 
 [ 4  6  7  9 18 19]
[ 1  2  4  5  6  7  8  9 10 11 13 14 16 17 18 19 20 22 23 24 26 27 28 29] 
 [ 0  3 12 15 21 25]


In [67]:
train

array([ 0,  1,  3,  4,  5,  6,  7,  8,  9, 11, 12, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 25, 27, 29])

In [126]:
'''for j in train:
    print([[x.iloc[i,0]]])''';

In [132]:
# Apply kfold
for train, test in kf.split(x, y):
    lr.fit(x[train], y[train])
    print('training acc:', lr.score(x[train], y[train]))
    print('testing acc:', lr.score(x[test], y[test]))
    print()

training acc: 0.9411949620562126
testing acc: 0.988169515729126

training acc: 0.9612542631539638
testing acc: 0.9257917429817739

training acc: 0.9635908373578711
testing acc: 0.9252385867407542

training acc: 0.9625173469912476
testing acc: 0.8785189123539608

training acc: 0.9540189535215173
testing acc: 0.9646120517676184

